type TauriInvoke = <T>(command: string, args?: Record<string, unknown>) => Promise<T>

declare global {
  interface Window {
    __TAURI__?: {
      core?: {
        invoke?: TauriInvoke
      }
    }
  }
}

/**
 * Saves generated bytes through the native dialog in the desktop app, while
 * preserving the regular browser download flow on the website.
 */
export async function downloadBytes(
  bytes: Uint8Array,
  filename: string,
  mimeType: string,
): Promise<boolean> {
  const invoke = window.__TAURI__?.core?.invoke
  if (invoke) {
    return invoke<boolean>('save_cursor_file', {
      fileName: filename,
      bytes: Array.from(bytes),
    })
  }

  const blob = new Blob([bytes.buffer as ArrayBuffer], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.click()
  window.setTimeout(() => URL.revokeObjectURL(url), 1000)
  return true
}

export function filenameStem(filename: string): string {
  const withoutExtension = filename.replace(/\.[^.]+$/, '')
  const withoutControlCharacters = Array.from(withoutExtension)
    .filter((character) => character.charCodeAt(0) >= 32)
    .join('')
  const safe = withoutControlCharacters
    .normalize('NFKC')
    .replace(/[<>:"/\\|?*]/g, '-')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')

  return safe || 'cursor'
}
